# This is a basic workflow to help you get started with Actions

name: brew std

# Controls when the workflow will run
on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-13

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Run a multi-line script
        shell: bash
        run: |
          sdl_image_formula=$(brew edit --print-path sdl_image)
          echo "--------------------------------------"
          echo $sdl_image_formula
