# This is a basic workflow to help you get started with Actions

name: Install PowerShell 7.4


on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-powershell:
    runs-on: windows-latest

    steps:
    - name: Check PowerShell version
      id: check-powershell
      run: |
        $currentVersion = $PSVersionTable.PSVersion
        Write-Output "Current PowerShell version: $currentVersion"
  
    - name: Download and Install PowerShell 7.4
      if: steps.check-powershell.outcome == 'success'
      run: |
        $url = "https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/PowerShell-7.4.0-win-x64.zip"
        $downloadPath = "$env:TEMP\PowerShell-7.4.0-win-x64.zip"
        $extractPath = "C:\Program Files\PowerShell\7.4"

        Invoke-WebRequest -Uri $url -OutFile $downloadPath
        Expand-Archive -Path $downloadPath -DestinationPath $extractPath -Force
        $env:Path = "$extractPath;$env:Path"
        Write-host $env:Path
     
        $newPath = "$extractPath;$env:Path"
        [System.Environment]::SetEnvironmentVariable('Path', $newPath, [System.EnvironmentVariableTarget]::Process)
        
        Add-Content -Path $profile -Value "`$env:Path = \"$newPath\""

    - name: Verify PowerShell version
      run: |
        pwsh --version
        pwsh
        $installedVersion = $PSVersionTable.PSVersion
        Write-Output "Installed PowerShell version: $installedVersion"
