# This is a basic workflow to help you get started with Actions

name: Install PowerShell 7.4


on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-powershell:
    runs-on: windows-latest

    steps:
    - name: Check PowerShell version
      run: |
        pwsh --version
        Get-ChildItem "C:\Program Files\PowerShell\7"
        $currentVersion = $PSVersionTable.PSVersion
        Write-Output "Current PowerShell version: $currentVersion"
  
    - name: Download and Install PowerShell 7.4
      shell: cmd
      run: |
        set "extractPath=C:\Program Files\PowerShell\7"
        curl -sLO https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/PowerShell-7.4.0-win-x64.zip
        RMDIR "%extractPath%" /S /Q
        7z x powershell-7.4.0-win-x64.zip -o"%extractPath%"
        

    - name: Verify PowerShell version
      run: |
        Get-ChildItem "C:\Program Files\PowerShell\7"
        pwsh --version
        $installedVersion = $PSVersionTable.PSVersion
        Write-Output "Installed PowerShell version: $installedVersion"
