
name: macos-14-test
on:
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-14

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Show tccDB
        run: |
          sqlite3 $HOME/Library/Application\ Support/com.apple.TCC/TCC.db "SELECT * FROM access;"

