# This is a basic workflow to help you get started with Actions

name: macos-ps-74

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    steps:
      - name: downgrade pwsh
        run: |
           curl -L -o powershell.pkg https://github.com/PowerShell/PowerShell/releases/download/v7.4.0/powershell-7.4.0-osx-x64.pkg
           sudo installer -pkg powershell.pkg -target /
           pwsh --version

      - name: downgrade pwsh
        run: |
           curl -L -o powershell.pkg https://github.com/PowerShell/PowerShell/releases/download/v7.2.17/powershell-7.2.17-osx-x64.pkg
           sudo installer -pkg powershell.pkg -target /
           pwsh --version
           

