# This is a basic workflow to help you get started with Actions

name: nuget config

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Runs a set of commands using the runners shell
      - name: check ~/.config/NuGet/NuGet.Config
        run: cat ~/.config/NuGet/NuGet.Config

      - name: Run a multi-line script
        run: nuget config -Set maxHttpRequestsPerSource=64

      - name: check ~/.config/NuGet/NuGet.Config
        run: cat ~/.config/NuGet/NuGet.Config
