# This is a basic workflow to help you get started with Actions

name: powershell-test

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Run a multi-line script
        shell: powershell
        run: |
          Writee-Host 'Error'
          Write-Host 'Test'
