# This is a basic workflow to help you get started with Actions

name: powershell 7.4 test

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-powershell:
    runs-on: ubuntu-latest
    steps:

    - name: Remove Powershell
      run: sudo apt-get remove powershell

    - name: Install PowerShell
      run: |
        sudo apt-get update

        curl https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update

        sudo apt-get install -y powershell=7.4.0-1.deb

    - name: Verify PowerShell installation
      run: pwsh --version

    - name: Run PowerShell script
      run: |
        param (
            [int]$TotalCount = 50
        )

        function My-LongRunningTask {
            param (
                [int]$Total
            )

            for ($i = 1; $i -le $Total; $i++) {
                Start-Sleep -Seconds 1
                Write-Progress -PercentComplete (($i / $Total) * 100) -Status "Processing Item $i/$Total"
            }
        }

        My-LongRunningTask -Total $TotalCount -ProgressAction {
            param ($ProgressRecord)
            Write-Host "Progress: $($ProgressRecord.PercentComplete)% - $($ProgressRecord.Status)"
        }

        Write-Host "Task completed."
