# This is a basic workflow to help you get started with Actions

name: powershell 7.4 test

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install-powershell:
    runs-on: ubuntu-latest
    steps:

    - name: Install PowerShell 7.4
      run: |
        sudo apt-get remove powershell
        curl https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell=7.4.0-1.deb
        pwsh --version

    - name: Install PowerShell 7.2
      run: |
        sudo apt-get remove powershell
        curl https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -o packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell=7.2.17-1.deb
        pwsh --version
  
