# This is a basic workflow to help you get started with Actions

name: ubnt-cifs

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: show lsmod before
        run: lsmod 
      - name: Install cifs-utils
        run: sudo apt update -y && sudo apt install -y cifs-utils
      - name: show lsmod
        run: lsmod
