# This is a basic workflow to help you get started with Actions

name: windows_test

on:


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Setup Debian
      uses: Vampire/setup-wsl@v2
      with:
        distribution: Debian
        additional-packages: python3-pip
    - name: Install HTTPie in Debian
      shell: wsl-bash {0}
      run: python3 -m pip install --upgrade pip wheel httpie
    - name: Install HTTPie in Windows
      run: python -m pip install --upgrade pip wheel httpie
    - name: Check Python version in Debian
      shell: wsl-bash {0}
      run: python3 --version
    - name: Check Python version in Windows
      run: python --version
    - name: Check HTTPie version in Debian
      shell: wsl-bash {0}
      run: http --version
    - name: Check HTTPie version in Windows
      run: http --version
    - name: Check http connection to store.rg-adguard.net
      run: http -f POST https://store.rg-adguard.net/api/GetFiles type=ProductId url=9p804crf0395
      if: always()
    - name: Check WSL http connection to store.rg-adguard.net
      shell: wsl-bash {0}
      run: http -f POST https://store.rg-adguard.net/api/GetFiles type=ProductId url=9p804crf0395
      if: always()

