

name: vision_os_test

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-14
    continue-on-error: true
    strategy:
      matrix:
        version: ["15.0.1", "15.2", "15.1"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
         xcode-version: ${{ matrix.version }}
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: cmake -G "Xcode" -DCMAKE_SYSTEM_NAME="visionOS"
