# This is a basic workflow to help you get started with Actions

name: windows-ports

# Controls when the workflow will run
on:

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:

      - name: netstat
        run: |
         Write-Host "Search 500"
         netstat -an | Select-String "500"
         Write-host "Search 4500"
         netstat -an | Select-String "4500"
         

